version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: src/nsupdate/Dockerfile
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/nsupdate/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev